version: "3.7"

services:
  hsb-app:
    restart: always
    command : npm start
    container_name: front
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    stdin_open: true